In [2]:
import numpy as np

vector = np.array([5, 10, 15, 20, 25])
vector == 10

array([False,  True, False, False, False], dtype=bool)

In [4]:
matrix = np.array([
    [5, 10],
    [20, 25],
    [35, 40]
])
matrix == 25

array([[False, False],
       [False,  True],
       [False, False]], dtype=bool)

In [5]:
print(vector[vector == 10])

[10]


In [6]:
second_column_25 = matrix[1, :] == 25
print(second_column_25)
print(matrix[matrix[1, :] == 25])

[False  True]
[[20 25]]


C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 2
  app.launch_new_instance()


In [7]:
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)
vector[equal_to_ten_or_five] = 99
print(vector)

[ True  True False False False]
[99 99 15 20 25]


In [8]:
print(matrix[:, 1] == 25)
print(matrix[matrix[:, 1] == 25])

[False  True False]
[[20 25]]


In [9]:
vector = np.array(["2", "4", "6"])
print(vector.dtype)
print(vector)
vector = vector.astype(float)
print(vector.dtype)
print(vector)

<U1
['2' '4' '6']
float64
[ 2.  4.  6.]


In [10]:
vector = np.array([5, 10, 15, 20, 25, 30])
print(vector.sum())
print(vector.max())
print(vector.min())
print(vector.mean())

105
30
5
17.5


In [11]:
matrix = np.array([
    [5, 10],
    [15, 20],
    [25, 30]
])
# 1 means that we want to perform the operation on each row, and 0 means on each column
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))

[45 60]
[15 35 55]


In [12]:
world_alcohol = np.genfromtxt('world_alcohol.txt', delimiter=',', dtype=np.str)
print(world_alcohol)
is_value_empty = np.isnan(world_alcohol[:, 4])
# print(is_value_empty)

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ..., 
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''