In [2]:
import numpy as np

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
a.shape

(3, 5)

In [11]:
a.ndim

2

In [14]:
a.dtype.name

'int32'

In [16]:
a.size

15

In [18]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [20]:
np.ones((2, 3, 4), dtype=np.int64)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [22]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [24]:
np.arange(10, 31, 5)

array([10, 15, 20, 25, 30])

In [28]:
np.arange(5, 101, 5).reshape(2, 2, 5)

array([[[  5,  10,  15,  20,  25],
        [ 30,  35,  40,  45,  50]],

       [[ 55,  60,  65,  70,  75],
        [ 80,  85,  90,  95, 100]]])

In [32]:
np.random.random((2,3))

array([[ 0.36884491,  0.51401081,  0.34192409],
       [ 0.99229337,  0.55245891,  0.06134548]])

In [36]:
# 0~100 取五個
np.linspace(0, 100, 5)

array([   0.,   25.,   50.,   75.,  100.])

In [39]:
from numpy import pi
np.linspace(0, 2*pi, 20)

array([ 0.        ,  0.33069396,  0.66138793,  0.99208189,  1.32277585,
        1.65346982,  1.98416378,  2.31485774,  2.64555171,  2.97624567,
        3.30693964,  3.6376336 ,  3.96832756,  4.29902153,  4.62971549,
        4.96040945,  5.29110342,  5.62179738,  5.95249134,  6.28318531])

In [40]:
np.sin(np.linspace(0, 2*pi, 20))

array([  0.00000000e+00,   3.24699469e-01,   6.14212713e-01,
         8.37166478e-01,   9.69400266e-01,   9.96584493e-01,
         9.15773327e-01,   7.35723911e-01,   4.75947393e-01,
         1.64594590e-01,  -1.64594590e-01,  -4.75947393e-01,
        -7.35723911e-01,  -9.15773327e-01,  -9.96584493e-01,
        -9.69400266e-01,  -8.37166478e-01,  -6.14212713e-01,
        -3.24699469e-01,  -2.44929360e-16])

In [46]:
# 矩陣相減
a = np.array([20, 21, 22, 23])
b = np.arange(4)
print(a)
print(b)
print(a-b)
print(b**2)
print(a > 20)

[20 21 22 23]
[0 1 2 3]
[20 20 20 20]
[0 1 4 9]
[False  True  True  True]


In [49]:
a = np.array([
    [1, 1],
    [0, 1]
])
b = np.array([
    [2, 1],
    [3, 4]
])
print(a)
print(b)
print(a*b)

[[1 1]
 [0 1]]
[[2 1]
 [3 4]]
[[2 1]
 [0 4]]


In [52]:
print(a.dot(b))
print(np.dot(a, b))

[[5 5]
 [3 4]]
[[5 5]
 [3 4]]
