In [10]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [11]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [12]:
np.sqrt(a)

array([ 0.        ,  1.        ,  1.41421356])

In [13]:
np.square(a)

array([0, 1, 4], dtype=int32)

In [20]:
a = np.floor(10*np.random.random((3, 4)))
a

array([[ 4.,  4.,  9.,  0.],
       [ 1.,  8.,  8.,  5.],
       [ 6.,  7.,  8.,  7.]])

In [22]:
a.shape

(3, 4)

In [24]:
a.ravel()

array([ 4.,  4.,  9.,  0.,  1.,  8.,  8.,  5.,  6.,  7.,  8.,  7.])

In [28]:
a.shape = (6, 2)
a

array([[ 4.,  4.],
       [ 9.,  0.],
       [ 1.,  8.],
       [ 8.,  5.],
       [ 6.,  7.],
       [ 8.,  7.]])

In [30]:
a.T

array([[ 4.,  9.,  1.,  8.,  6.,  8.],
       [ 4.,  0.,  8.,  5.,  7.,  7.]])

In [33]:
a.resize(6, 2)
a

array([[ 4.,  4.],
       [ 9.,  0.],
       [ 1.,  8.],
       [ 8.,  5.],
       [ 6.,  7.],
       [ 8.,  7.]])

In [40]:
# 兩矩陣拼接
a = np.floor(10*np.random.random((2, 2)))
b = np.floor(10*np.random.random((2, 2)))
print('-----a------')
print(a)
print('-----b------')
print(b)
print('---vstack(a, b)----')
print(np.vstack((a, b)))
print('---hstack(a, b)----')
print(np.hstack((a, b)))

-----a------
[[ 9.  2.]
 [ 1.  6.]]
-----b------
[[ 1.  7.]
 [ 4.  2.]]
---vstack(a, b)----
[[ 9.  2.]
 [ 1.  6.]
 [ 1.  7.]
 [ 4.  2.]]
---hstack(a, b)----
[[ 9.  2.  1.  7.]
 [ 1.  6.  4.  2.]]


In [47]:
# 切分
a = np.floor(10 * np.random.random((2, 12)))
print(a)
print('----hsplit(a, 3)----')
print(np.hsplit(a, 3))
print('----hsplit(a, (3, 6))----')
print(np.hsplit(a, (3, 6)))
a = np.floor(10*np.random.random((12, 2)))
print('---a---')
print(a)
print('----vsplit(a, 3)----')
print(np.vsplit(a, 3))

[[ 8.  3.  4.  7.  8.  6.  1.  7.  2.  7.  5.  3.]
 [ 4.  1.  7.  9.  4.  7.  1.  0.  4.  0.  2.  6.]]
----hsplit(a, 3)----
[array([[ 8.,  3.,  4.,  7.],
       [ 4.,  1.,  7.,  9.]]), array([[ 8.,  6.,  1.,  7.],
       [ 4.,  7.,  1.,  0.]]), array([[ 2.,  7.,  5.,  3.],
       [ 4.,  0.,  2.,  6.]])]
----hsplit(a, (3, 6))----
[array([[ 8.,  3.,  4.],
       [ 4.,  1.,  7.]]), array([[ 7.,  8.,  6.],
       [ 9.,  4.,  7.]]), array([[ 1.,  7.,  2.,  7.,  5.,  3.],
       [ 1.,  0.,  4.,  0.,  2.,  6.]])]
---a---
[[ 8.  8.]
 [ 5.  1.]
 [ 4.  5.]
 [ 6.  1.]
 [ 4.  5.]
 [ 7.  1.]
 [ 7.  3.]
 [ 5.  8.]
 [ 7.  3.]
 [ 9.  9.]
 [ 7.  4.]
 [ 3.  1.]]
----vsplit(a, 3)----
[array([[ 8.,  8.],
       [ 5.,  1.],
       [ 4.,  5.],
       [ 6.,  1.]]), array([[ 4.,  5.],
       [ 7.,  1.],
       [ 7.,  3.],
       [ 5.,  8.]]), array([[ 7.,  3.],
       [ 9.,  9.],
       [ 7.,  4.],
       [ 3.,  1.]])]


In [51]:
# np 陣列是 call by ref
a = np.arange(12)
b = a
print('----b is a?----')
print(b is a)
print('--b shape = 3, 4  a shape =?--')
b.shape = 3, 4
print(a.shape)

----b is a?----
True
b shape = 3, 4  a shape =?
(3, 4)


In [56]:
# 淺拷貝
c = a.view()
print('----c is a?----')
print(c is a)
c.shape = 2, 6
c[0, 4] = 999
print('--c[0, 4] = 999--')
print(a)

----c is a?----
False
--c[0, 4] = 999--
[[  0   1   2   3]
 [999   5   6   7]
 [  8   9  10  11]]


In [58]:
# 深拷貝
d = a.copy()
print("d is a?")
print(d is a)
d[0, 0] = 99999
print(a)

d is a?
False
[[  0   1   2   3]
 [999   5   6   7]
 [  8   9  10  11]]
